import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/pricingengine">PricingEngine</Link>
        </li>
        <li>
          <Link to="/orderdetailview">Orderdetailview</Link>
        </li>
        <li>
          <Link to="/baslinereporting">BaslineReporting</Link>
        </li>
        <li>
          <Link to="/projectportfolio">ProjectPortfolio</Link>
        </li>
        <li>
          <Link to="/employeelogin">Employeelogin</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
